<Project Sdk="Microsoft.NET.Sdk">

  <!-- Exemplo: N-Rainhas de 4x4 até 8x8. -->
  <!-- Para rodar: dotnet run (dentro desta pasta). -->

  <PropertyGroup>
    <AssemblyName>NRainhasLongo</AssemblyName>
    <RootNamespace>NRainhasLongo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Enneal.Algoritmos.NRainhas/Enneal.Algoritmos.NRainhas.csproj" />
  </ItemGroup>

</Project>
